---

- include: create_swap_file.yml
  when: create_swap_file
  tags: swap

- name: Ensure bash, OpenSSL, and libssl are the latest versions
  apt: name={{ item }} update_cache={{ update_apt_cache }} state=latest
  with_items:
    - bash
    - openssl
    - libssl-dev
    - libssl-doc
  tags: packages

- name: Install base packages
  apt: name={{ item }} update_cache={{ update_apt_cache }} force=yes state=latest
  with_items:
    - build-essential
    - ntp
    - htop
    - git
    - python3-dev
    - python3-pip
    - python3-pycurl
    - python3-venv
    - libyaml-dev
    - python3-numpy-dev
    - python3-numpy
    - python3-yaml
    - pkg-config
    - libffi-dev
    - libxml2-dev
    - libjpeg-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
  tags: packages

- name: Upgrade pip
  pip: name=pip state=latest executable=pip3
  tags: packages
