---

- name: Create a {{ application_name }} deployment virtual machine via vagrant
  hosts: all
  become: yes
  become_user: root
  remote_user: vagrant
  vars:
    - update_apt_cache: yes
  vars_files:
    - vars/base.yml
    - vars/vagrant.yml
    # - vars/ssh.yml
  roles:
    - base
    - migibert.terraform
    - avanov.pyenv
    - kubespray_repo
  tasks:
    - name: Copy generate_ssh script
      become_user: vagrant
      copy:
        src: files/generate_ssh.sh
        dest: "{{ vagrant_user_home }}/generate_ssh.sh"
        mode: '0777'
    - name: Copy aws_infrastructure_customize script
      become_user: vagrant
      copy:
        src: files/aws_infrastructure_customize.sh
        dest: "{{ vagrant_user_home }}/aws_infrastructure_customize.sh"
        mode: '0777'
    - name: Install awscli
      apt: name=awscli update_cache={{ update_apt_cache }} force=yes state=latest
